Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OcelotAPIGateway"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OrderAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OrderGrpc"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OrderProcessor"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Payment"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Shipment"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Warehouse"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\WarehouseAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\WebUI"
Start-Process "http://localhost:8011/"