Start-Process -FilePath "cmd" -ArgumentList "/c docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.11-management" -WorkingDirectory ".\"
Start-Process -FilePath "cmd" -ArgumentList "/c docker run -it --rm --name mongo -p 27017:27017 mongo:latest" -WorkingDirectory ".\"
Start-Sleep -Seconds 15
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\CatalogAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\CustomerAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Notifications"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OcelotAPIGateway"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OrderAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OrderGrpc"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\OrderProcessor"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Payment"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Shipment"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\ShoppingCartAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\Warehouse"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\WarehouseAPI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\WebUI"
Start-Process -FilePath "cmd" -ArgumentList "/c dotnet run" -WorkingDirectory ".\WebUIAggregatorAPI"
Start-Process "http://localhost:8011/"