version: '3.4'

services:
  notifications:
    image: ${DOCKER_REGISTRY-}notifications:1.16.0
    build:
      context: .
      dockerfile: Notifications/Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi:1.16.0
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile

  orderprocessor:
    image: ${DOCKER_REGISTRY-}orderprocessor:1.16.0
    build:
      context: .
      dockerfile: OrderProcessor/Dockerfile

  warehouse:
    image: ${DOCKER_REGISTRY-}warehouse:1.16.0
    build:
      context: .
      dockerfile: Warehouse/Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi:1.16.0
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway:1.16.0
    build:
      context: .
      dockerfile: OcelotAPIGateway/Dockerfile
      
  rabbitmq:
    image: rabbitmq:management:1.16.0
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmqdata: