version: '3.4'

services:
  shopdb:
    image: mongo

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogAPI/Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile

  notifications:
    image: ${DOCKER_REGISTRY-}notifications
    build:
      context: .
      dockerfile: Notifications/Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile

  ordergrpc:
    image: ${DOCKER_REGISTRY-}ordergrpc
    build:
      context: .
      dockerfile: OrderGrpc/Dockerfile

  orderprocessor:
    image: ${DOCKER_REGISTRY-}orderprocessor
    build:
      context: .
      dockerfile: OrderProcessor/Dockerfile

  payment:
    image: ${DOCKER_REGISTRY-}payment
    build:
      context: .
      dockerfile: Payment/Dockerfile

  shipment:
    image: ${DOCKER_REGISTRY-}shipment
    build:
      context: .
      dockerfile: Shipment/Dockerfile

  shoppingcartapi:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: ShoppingCartAPI/Dockerfile

  warehouse:
    image: ${DOCKER_REGISTRY-}warehouse
    build:
      context: .
      dockerfile: Warehouse/Dockerfile

  warehouseapi:
    image: ${DOCKER_REGISTRY-}warehouseapi
    build:
      context: .
      dockerfile: WarehouseAPI/Dockerfile

  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: WebUI/Dockerfile

  webuiaggregatorapi:
    image: ${DOCKER_REGISTRY-}webuiaggregatorapi
    build:
      context: .
      dockerfile: WebUIAggregatorAPI/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotAPIGateway/Dockerfile

  feedbackapi:
    image: ${DOCKER_REGISTRY-}feedbackapi
    build:
      context: .
      dockerfile: FeedbackAPI/Dockerfile

  discount:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Discount/Dockerfile

  search:
    image: ${DOCKER_REGISTRY-}search
    build:
      context: .
      dockerfile: Search/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

volumes:
  mongo_data:
  rabbitmqdata: