apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-pod
  labels:
    app: catalogapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: catalogapi-app
  template:
    metadata: 
      labels:
        app: catalogapi-app
    spec:
      containers:
        - name: catalogapi
          image: ivanenkomak/catalogapi:1.0
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
