apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-pod
  labels:
    app: discountapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: discountapi-app
  template:
    metadata: 
      labels:
        app: discountapi-app
    spec:
      containers:
        - name: discountapi
          image: ivanenkomak/discountapi:latest
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
            - name: ApiSettings__GatewayAddress
              value: "http://ocelotapigateway"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
