apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-pod
  labels:
    app: discount
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: discount-app
  template:
    metadata: 
      labels:
        app: discount-app
    spec:
      containers:
        - name: discount
          image: ivanenkomak/discount:20230827071709
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
            - name: ApiSettings__GatewayAddress
              value: "http://ocelotapigateway"
            - name: RabbitMQSettings__AMQPConnectionString
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: ServerSettings__ApplicationUrl
              value: ":80"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
