apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: my-cluster
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer
