apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-pod
  labels:
    app: s5
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: jaeger-app
  template:
    metadata: 
      labels:
        app: jaeger-app
    spec:
      containers:
        - name: jaeger-container
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4317
            - containerPort: 16686
