apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: LoadBalancer
  selector:
    app: jaeger-app
  ports:
    - name: connect
      port: 4317
      targetPort: 4317
    - name: management
      port: 16686
      targetPort: 16686