apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-pod
  labels:
    app: s1
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: notifications-app
  template:
    metadata: 
      labels:
        app: notifications-app
    spec:
      volumes:
        - name: appsettings-volume
          configMap:
            name: app-configmap
      containers:
        - name: notifications-container
          image: notifications:1.16.0
          imagePullPolicy: Never
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.k8s.json
              subPath: appsettings.k8s.json
          ports:
            - containerPort: 80
