apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-pod
  labels:
    app: notifications
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: notifications-app
  template:
    metadata: 
      labels:
        app: notifications-app
    spec:
      volumes:
        - name: appsettings-volume
          configMap:
            name: app-configmap
      containers:
        - name: notifications
          image: ivanenkomak/notifications:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
