apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigateway-pod
  labels:
    app: ocelotapigateway
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ocelotapigateway-app
  template:
    metadata: 
      labels:
        app: ocelotapigateway-app
    spec:
      volumes:
        - name: ocelot-volume
          configMap:
            name: ocelot-configmap
      containers:
        - name: ocelotapigateway
          image: ivanenkomak/ocelotapigateway:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: k8s
          volumeMounts:
            - name: ocelot-volume
              mountPath: /app/ocelot.k8s.json
              subPath: ocelot.k8s.json
          ports:
            - containerPort: 80
