apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-configmap
data:
  ocelot.k8s.json: |-
    {
        "Routes": [
            // Order API
            {
                "UpstreamPathTemplate": "/gateway/Order",
                "UpstreamHttpMethod": [ "GET", "POST" ],
                "DownstreamPathTemplate": "/api/Order",
                "DownstreamScheme": "http",
                "DownstreamHostAndPorts": [
                    {
                        "Host": "orderapi-service",
                        "Port": 8000
                    }
                ],
                "FileCacheOptions": { "TtlSeconds": 30 }
            },
            // Customer API
            {
                "UpstreamPathTemplate": "/gateway/Customer",
                "UpstreamHttpMethod": [ "GET", "POST" ],
                "DownstreamPathTemplate": "/api/Customer",
                "DownstreamScheme": "http",
                "DownstreamHostAndPorts": [
                    {
                        "Host": "customerapi-service",
                        "Port": 8001
                    }
                ],
                "FileCacheOptions": { "TtlSeconds": 30 }
            }
        ],
        "GlobalConfiguration": {
            "BaseUrl": "http://localhost:8010"
        }
    }