apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-pod
  labels:
    app: orderapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: orderapi-app
  template:
    metadata: 
      labels:
        app: orderapi-app
    spec:
      containers:
        - name: orderapi
          image: ivanenkomak/orderapi:latest
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80