apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessor-pod
  labels:
    app: orderprocessor
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: orderprocessor-app
  template:
    metadata: 
      labels:
        app: orderprocessor-app
    spec:
      containers:
        - name: orderprocessor
          image: ivanenkomak/orderprocessor:latest
          env:
            - name: GrpcSettings__OrderGrpcUrl
              value: "http://ordergrpc"
            - name: RabbitMQ__HostName
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: RabbitMQ__Port
              value: 5672
          imagePullPolicy: Always
          ports:
            - containerPort: 80
