apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordergrpc-pod
  labels:
    app: ordergrpc
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ordergrpc-app
  template:
    metadata: 
      labels:
        app: ordergrpc-app
    spec:
      containers:
        - name: ordergrpc
          image: ivanenkomak/ordergrpc:latest
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
