apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pod
  labels:
    app: prometheus
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: prometheus-app
  template:
    metadata: 
      labels:
        app: prometheus-app
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: LoadBalancer
  selector:
    app: prometheus-app
  ports:
    - port: 9090
      targetPort: 9090