apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-pod
  labels:
    app: search
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: search-app
  template:
    metadata: 
      labels:
        app: search-app
    spec:
      containers:
        - name: search
          image: search:latest
          env:
            - name: RUN_MODE
              value: "production"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
