apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-pod
  labels:
    app: shipment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: shipment-app
  template:
    metadata: 
      labels:
        app: shipment-app
    spec:
      containers:
        - name: shipment
          image: ivanenkomak/shipment:latest
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
            - name: Otlp__Endpoint
              value: "http://jaeger:4317"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: Always
          ports:
            - containerPort: 80
