apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcartapi-pod
  labels:
    app: shoppingcartapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: shoppingcartapi-app
  template:
    metadata: 
      labels:
        app: shoppingcartapi-app
    spec:
      containers:
        - name: shoppingcartapi
          image: ivanenkomak/shoppingcartapi:1.0
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80