apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouseapi-pod
  labels:
    app: warehouseapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: warehouseapi-app
  template:
    metadata: 
      labels:
        app: warehouseapi-app
    spec:
      containers:
        - name: warehouseapi
          image: ivanenkomak/warehouseapi:1.1
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://shopdb:27017"
            - name: ApiSettings__GatewayAddress
              value: "http://ocelotapigateway"
          envFrom:
            - secretRef:
                name: mongo-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
