apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-pod
  labels:
    app: webui
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webui-app
  template:
    metadata: 
      labels:
        app: webui-app
    spec:
      containers:
        - name: webui
          image: ivanenkomak/webui:latest
          env:
            - name: ApiSettings__GatewayAddress
              value: "http://ocelotapigateway"
            - name: Otlp__Endpoint
              value: "http://simplest-collector:4317"
          imagePullPolicy: Always
          ports:
            - containerPort: 80