apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-pod
  labels:
    app: s2
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: orderapi-app
  template:
    metadata: 
      labels:
        app: orderapi-app
    spec:
      volumes:
        - name: appsettings-volume
          configMap:
            name: orderapi-cfg
      containers:
        - name: orderapi-container
          image: orderapi
          imagePullPolicy: Never
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.k8s.json
              subPath: appsettings.k8s.json
          ports:
            - containerPort: 80
