apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
    - name: connect
      port: 8080
      targetPort: 5672
    - name: management
      port: 8081
      targetPort: 15672