apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-pod
  labels:
    app: s4
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: warehouse-app
  template:
    metadata: 
      labels:
        app: warehouse-app
    spec:
      volumes:
        - name: appsettings-volume
          configMap:
            name: warehouse-cfg
      containers:
        - name: warehouse-container
          image: warehouse
          imagePullPolicy: Never
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.k8s.json
              subPath: appsettings.k8s.json
          ports:
            - containerPort: 80
