debug = true

[apiserver]
application_url = "localhost:8004"
hostname = "localhost"

[apisettings]
gateway_address = "localhost:8003"

[database]
connection_string = "mongodb://localhost:27017"
database_name = "OrderDb"
collection_name = "Orders"

[rabbitmqsettings]
ampq_connection_string = "amqp://guest:guest@localhost:5672"