debug = true

[apiserver]
application_url = "0.0.0.0:80"
hostname = "localhost"

[apisettings]
gateway_address = "http://ocelotapigateway"

[database]
connection_string = "mongodb://shopdb:27017"
database_name = "OrderDb"
collection_name = "Orders"

[rabbitmqsettings]
ampq_connection_string = "amqp://guest:guest@rabbitmq:5672"