name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - image: ivanenkomak/catalogapi
            dockerfile: CatalogAPI/Dockerfile
          - image: ivanenkomak/customerapi
            dockerfile: CustomerAPI/Dockerfile
          - image: ivanenkomak/notifications
            dockerfile: Notifications/Dockerfile
          - image: ivanenkomak/ocelotapigateway
            dockerfile: OcelotAPIGateway/Dockerfile
          - image: ivanenkomak/orderapi
            dockerfile: OrderAPI/Dockerfile
          - image: ivanenkomak/ordergrpc
            dockerfile: OrderGrpc/Dockerfile
          - image: ivanenkomak/orderprocessor
            dockerfile: OrderProcessor/Dockerfile
          - image: ivanenkomak/payment
            dockerfile: Payment/Dockerfile
          - image: ivanenkomak/shipment
            dockerfile: Shipment/Dockerfile
          - image: ivanenkomak/shoppingcartapi
            dockerfile: ShoppingCartAPI/Dockerfile
          - image: ivanenkomak/warehouse
            dockerfile: Warehouse/Dockerfile
          - image: ivanenkomak/warehouseapi
            dockerfile: WarehouseAPI/Dockerfile
          - image: ivanenkomak/webui
            dockerfile: WebUI/Dockerfile
          - image: ivanenkomak/webuiaggregatorapi
            dockerfile: WebUIAggregatorAPI/Dockerfile
          - image: ivanenkomak/feedbackapi
            dockerfile: FeedbackAPI/Dockerfile
          - image: ivanenkomak/discountapi
            dockerfile: Discount/Dockerfile
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
