# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Format
      shell: pwsh
      run: |
        git fetch origin main --depth=1
        
        $files = git diff --name-only --diff-filter=ACMRT origin/main | Where-Object { $_ -match '\.cs$' }
        
        if ($files.Count -gt 0) {
            Write-Host "Running dotnet format on changed files..."
            dotnet format --include $files -v diagnostic --verify-no-changes
        } else {
            Write-Host "No C# files to format."
        }

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
