name: Docker Image CI - Warehouse

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - 'Warehouse/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Warehouse/**'
      - 'Common/**'

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Generate Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ivanenkomak/warehouse
      - name: Build and push
        run: |
          TIMESTAMP="${{ steps.timestamp.outputs.timestamp }}"
          IMAGE_TAG="ivanenkomak/warehouse:${TIMESTAMP}"
          DOCKERFILE="Warehouse/Dockerfile"
          echo "Building Docker image with timestamp tag: ${IMAGE_TAG}"
          docker buildx build -t "${IMAGE_TAG}" --file "${DOCKERFILE}" . --push
